### ISSUE TITLE
Grouping Capability

### ISSUE THREAD

**Issue by rob-white** [rob-white/SlimGrid#6]
Create an example and verify everything still works correctly for row grouping.

http://mleibman.github.io/SlickGrid/examples/example-grouping

**Comment by rob-white** [comment]
Added in 0629d59b6670cddc6815b41cbd5255d045c69cef

[Example here](http://rob-white.github.io/SlimGrid/examples/example-5.htm)

**Comment by madanielecd** [comment]
Hi Rob,

Thx for this fork of slickgrid! Its just beautiful!
Remark/question: I'm not able to use the collapse/expand all groups function in slimgrid (f.e. collapseAllGroups(level)). Is this still possible in slimgrid?

With kind regards
Marlon

**Comment by rob-white** [comment]
Hey Marlon, 

Glad you like it!

This functionality should work and is most likely a bug. I'll take a look at it and see if I can find a fix.

**Comment by rob-white** [comment]
@madanielecd - I updated the grouping/aggregates example with `collapseAllGroups()` and `expandAllGroups()`. Let me know if that's what you were looking for.

**Comment by madanielecd** [comment]
Yes perfect!
I see I had to use 'grid.dataview()' first instead of 'dataview.' only.

Thx for clearing this up!

With kind regards,
Marlon
